# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/adder.xdc

# IP: ip/full_adder_1/full_adder_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1 || ORIG_REF_NAME==full_adder_1} -quiet] -quiet
