  set_property PACKAGE_PIN W19 [get_ports btnl]
set_property IOSTANDARD LVCMOS33 [get_ports btnl]
set_property PACKAGE_PIN T17 [get_ports btnr]
set_property IOSTANDARD LVCMOS33 [get_ports btnr]



set_property PACKAGE_PIN V7 [get_ports dp]
set_property IOSTANDARD LVCMOS33 [get_ports dp]
set_property PACKAGE_PIN U7 [get_ports display_out[0]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[0]]
set_property PACKAGE_PIN V5 [get_ports display_out[1]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[1]]
set_property PACKAGE_PIN U5 [get_ports display_out[2]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[2]]
set_property PACKAGE_PIN V8 [get_ports display_out[3]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[3]]
set_property PACKAGE_PIN U8 [get_ports display_out[4]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[4]]
set_property PACKAGE_PIN W6 [get_ports display_out[5]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[5]]
set_property PACKAGE_PIN W7 [get_ports display_out[6]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[6]]

set_property PACKAGE_PIN U2 [get_ports select[0]]
set_property IOSTANDARD LVCMOS33 [get_ports select[0]]
set_property PACKAGE_PIN U4 [get_ports select[1]]
set_property IOSTANDARD LVCMOS33 [get_ports select[1]]
set_property PACKAGE_PIN V4 [get_ports select[2]]
set_property IOSTANDARD LVCMOS33 [get_ports select[2]]
set_property PACKAGE_PIN W4 [get_ports select[3]]
set_property IOSTANDARD LVCMOS33 [get_ports select[3]]

set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5}[get_ports clk]
