set_property PACKAGE_PIN U18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]
set_property PACKAGE_PIN V17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN V7 [get_ports dp]
set_property IOSTANDARD LVCMOS33 [get_ports dp]
set_property PACKAGE_PIN U7 [get_ports display_out[0]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[0]]
set_property PACKAGE_PIN V5 [get_ports display_out[1]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[1]]
set_property PACKAGE_PIN U5 [get_ports display_out[2]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[2]]
set_property PACKAGE_PIN V8 [get_ports display_out[3]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[3]]
set_property PACKAGE_PIN U8 [get_ports display_out[4]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[4]]
set_property PACKAGE_PIN W6 [get_ports display_out[5]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[5]]
set_property PACKAGE_PIN W7 [get_ports display_out[6]]
set_property IOSTANDARD LVCMOS33 [get_ports display_out[6]]

set_property PACKAGE_PIN U2 [get_ports select[0]]
set_property IOSTANDARD LVCMOS33 [get_ports select[0]]
set_property PACKAGE_PIN U4 [get_ports select[1]]
set_property IOSTANDARD LVCMOS33 [get_ports select[1]]
set_property PACKAGE_PIN V4 [get_ports select[2]]
set_property IOSTANDARD LVCMOS33 [get_ports select[2]]
set_property PACKAGE_PIN W4 [get_ports select[3]]
set_property IOSTANDARD LVCMOS33 [get_ports select[3]]

set_property PACKAGE_PIN W5 [get_ports rclk]
set_property IOSTANDARD LVCMOS33 [get_ports rclk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5}[get_ports rclk]

set_property PACKAGE_PIN U16 [get_ports result[0]]
set_property IOSTANDARD LVCMOS33 [get_ports result[0]]
set_property PACKAGE_PIN E19 [get_ports result[1]]
set_property IOSTANDARD LVCMOS33 [get_ports result[1]]
set_property PACKAGE_PIN U19 [get_ports result[2]]
set_property IOSTANDARD LVCMOS33 [get_ports result[2]]
set_property PACKAGE_PIN V19 [get_ports result[3]]
set_property IOSTANDARD LVCMOS33 [get_ports result[3]]

set_property PACKAGE_PIN W18 [get_ports result[4]]
set_property IOSTANDARD LVCMOS33 [get_ports result[4]]
set_property PACKAGE_PIN U15 [get_ports result[5]]
set_property IOSTANDARD LVCMOS33 [get_ports result[5]]
set_property PACKAGE_PIN U14 [get_ports result[6]]
set_property IOSTANDARD LVCMOS33 [get_ports result[6]]
set_property PACKAGE_PIN V14 [get_ports result[7]]
set_property IOSTANDARD LVCMOS33 [get_ports result[7]]

set_property PACKAGE_PIN V13 [get_ports result[8]]
set_property IOSTANDARD LVCMOS33 [get_ports result[8]]
set_property PACKAGE_PIN V3 [get_ports result[9]]
set_property IOSTANDARD LVCMOS33 [get_ports result[9]]
set_property PACKAGE_PIN W3 [get_ports result[10]]
set_property IOSTANDARD LVCMOS33 [get_ports result[10]]
set_property PACKAGE_PIN U3 [get_ports result[11]]
set_property IOSTANDARD LVCMOS33 [get_ports result[11]]

set_property PACKAGE_PIN P3 [get_ports result[12]]
set_property IOSTANDARD LVCMOS33 [get_ports result[12]]
set_property PACKAGE_PIN N3 [get_ports result[13]]
set_property IOSTANDARD LVCMOS33 [get_ports result[13]]
set_property PACKAGE_PIN P1 [get_ports result[14]]
set_property IOSTANDARD LVCMOS33 [get_ports result[14]]
set_property PACKAGE_PIN L1 [get_ports result[15]]
set_property IOSTANDARD LVCMOS33 [get_ports result[15]]