# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/17727/Desktop/VivadoArea/pmd2/pmd2.cache/wt [current_project]
set_property parent.project_path C:/Users/17727/Desktop/VivadoArea/pmd2/pmd2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/17727/Desktop/VivadoArea/p138_2 [current_project]
set_property ip_output_repo c:/Users/17727/Desktop/VivadoArea/pmd2/pmd2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/17727/Desktop/VivadoArea/pmd2/pmd2.srcs/sources_1/new/pmd2.v
read_ip -quiet c:/Users/17727/Desktop/VivadoArea/pmd2/pmd2.srcs/sources_1/ip/p138_2_0/p138_2_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/17727/Desktop/VivadoArea/pmd2/pmd2.srcs/constrs_1/new/pmd2.xdc
set_property used_in_implementation false [get_files C:/Users/17727/Desktop/VivadoArea/pmd2/pmd2.srcs/constrs_1/new/pmd2.xdc]


synth_design -top pmd2 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pmd2.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pmd2_utilization_synth.rpt -pb pmd2_utilization_synth.pb"
