# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/17727/Desktop/VivadoArea/mul_4/mul_4.srcs/sources_1/ip/adder_1/adder_1.xci
# IP: The module: 'adder_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/17727/Desktop/VivadoArea/mul_4/mul_4.srcs/sources_1/ip/adder_1/sources_1/ip/full_adder_1/full_adder_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1 || ORIG_REF_NAME==full_adder_1} -quiet] -quiet

# XDC: c:/Users/17727/Desktop/VivadoArea/mul_4/mul_4.srcs/sources_1/ip/adder_1/constrs_1/new/adder.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/17727/Desktop/VivadoArea/mul_4/mul_4.srcs/sources_1/ip/adder_1/adder_1.xci
# IP: The module: 'adder_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/17727/Desktop/VivadoArea/mul_4/mul_4.srcs/sources_1/ip/adder_1/sources_1/ip/full_adder_1/full_adder_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1 || ORIG_REF_NAME==full_adder_1} -quiet] -quiet

# XDC: c:/Users/17727/Desktop/VivadoArea/mul_4/mul_4.srcs/sources_1/ip/adder_1/constrs_1/new/adder.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
